# site settings
title: 'Congreso Abierto - Parlamento Abierto Guatemala'
email: info@redciudadana.org
description: 'Plataforma de fiscalizacion legisltativa'
keywords: 'congreso, guatemala, fiscalización,control ciudadano,ciudadania,rendición de cuentas,rendicion de cuentas,cuenta,cuentas publicas,cuentas públicas,información pública,informacion publica,leyes,compromiso,congreso'
baseurl: '//congresoabierto.org/' # the subpath of your site, e.g. /blog/
url: 'http://congresoabierto.org/' # the base hostname & protocol for your site
analytics: 'UA-89669351-1' # google analytics tracking code
twitter_username: redxguate
launched: true
# build settings
markdown: kramdown
